### ISSUE TITLE
View path only

### ISSUE THREAD

**Issue by thomasarmel** [zdimension/graphrust#2]
Graph displaying consumes a lot of resources on my poor Lenovo Ideapad 720 laptop.
Implementing a feature to only display the paths would it be possible?

**Comment by zdimension** [comment]
Good idea, shouldn't be hard to do

**Comment by thomasarmel** [comment]
Actually no, and we could eventually access this feature by using an URL parameter (?graphonly=1)

**Comment by zdimension** [comment]
Graph now hides edges by default, which makes rendering smooth (>60fps) even on low-energy devices such as my phone, so this feature is moot.
